In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px
import warnings 
warnings.filterwarnings("ignore")

C:\Users\razas\anaconda3\Lib\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

In [2]:
movies=pd.read_csv("tmdb_5000_movies.csv")
credit=pd.read_csv("tmdb_5000_credits.csv")

In [3]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [4]:
credit.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [5]:
df = pd.merge(movies, credit, on="title", how="outer")
df

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,1500000,"[{""id"": 18, ""name"": ""Drama""}, {""id"": 9648, ""na...",http://www.hashtaghorror.com/,301325,[],de,#Horror,"Inspired by actual events, a group of 12 year ...",2.815228,"[{""name"": ""AST Studios"", ""id"": 75277}, {""name""...",...,90.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Death is trending.,#Horror,3.3,52,301325,"[{""cast_id"": 0, ""character"": ""Alex's 12-Step F...","[{""credit_id"": ""545bbac70e0a261fb6002329"", ""de..."
1,7500000,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...",http://500days.com,19913,"[{""id"": 248, ""name"": ""date""}, {""id"": 572, ""nam...",en,(500) Days of Summer,"Tom (Joseph Gordon-Levitt), greeting-card writ...",45.610993,"[{""name"": ""Fox Searchlight Pictures"", ""id"": 43...",...,95.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,It was almost like falling in love.,(500) Days of Summer,7.2,2904,19913,"[{""cast_id"": 4, ""character"": ""Tom Hansen"", ""cr...","[{""credit_id"": ""52fe47f99251416c750abaa5"", ""de..."
2,15000000,"[{""id"": 53, ""name"": ""Thriller""}, {""id"": 878, ""...",http://www.10cloverfieldlane.com/,333371,"[{""id"": 1930, ""name"": ""kidnapping""}, {""id"": 23...",en,10 Cloverfield Lane,"After a car accident, Michelle awakens to find...",53.698683,"[{""name"": ""Paramount Pictures"", ""id"": 4}, {""na...",...,103.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Monsters come in many forms.,10 Cloverfield Lane,6.8,2468,333371,"[{""cast_id"": 2, ""character"": ""Michelle"", ""cred...","[{""credit_id"": ""57627624c3a3680682000872"", ""de..."
3,1200000,"[{""id"": 18, ""name"": ""Drama""}]",NaN,345003,"[{""id"": 1568, ""name"": ""undercover""}, {""id"": 49...",en,10 Days in a Madhouse,"Nellie Bly, a 23 year-old reporter for Joseph ...",0.489271,[],...,111.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,10 Days in a Madhouse,4.3,5,345003,"[{""cast_id"": 2, ""character"": ""Nellie Bly"", ""cr...","[{""credit_id"": ""594efa1fc3a36832650455ff"", ""de..."
4,16000000,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",NaN,4951,"[{""id"": 497, ""name"": ""shakespeare""}, {""id"": 59...",en,10 Things I Hate About You,"Bianca, a tenth grader, has never gone on a da...",54.550275,"[{""name"": ""Mad Chance"", ""id"": 1757}, {""name"": ...",...,97.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,How do I loathe thee? Let me count the ways.,10 Things I Hate About You,7.3,1701,4951,"[{""cast_id"": 2, ""character"": ""Patrick Verona"",...","[{""credit_id"": ""52fe43e6c3a36847f807731d"", ""de..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4804,5600000,"[{""id"": 53, ""name"": ""Thriller""}, {""id"": 27, ""n...",http://www.rec2themovie.com/,10664,"[{""id"": 3684, ""name"": ""religion and supernatur...",es,[REC]Â²,"The action continues from [REC], with the medi...",22.341462,"[{""name"": ""Filmax"", ""id"": 3631}]",...,85.0,"[{""iso_639_1"": ""es"", ""name"": ""Espa\u00f1ol""}]",Released,Fear Revisited,[REC]Â²,6.4,489,10664,"[{""cast_id"": 3, ""character"": ""\u00c1ngela Vida...","[{""credit_id"": ""52fe439e9251416c7501783d"", ""de..."
4805,15000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 53, ""nam...",NaN,1946,"[{""id"": 282, ""name"": ""video game""}, {""id"": 215...",en,eXistenZ,A game designer on the run from assassins must...,21.928025,"[{""name"": ""Alliance Atlantis Communications"", ...",...,97.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Play it. Live it. Kill for it.,eXistenZ,6.7,475,1946,"[{""cast_id"": 3, ""character"": ""Allegra Geller"",...","[{""credit_id"": ""52fe4325c3a36847f803db2d"", ""de..."
4806,70000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/xxx/,7451,"[{""id"": 999, ""name"": ""sports car""}, {""id"": 186...",en,xXx,Xander Cage is your standard adrenaline junkie...,46.217769,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,124.0,"[{""iso_639_1"": ""cs"", ""name"": ""\u010cesk\u00fd""...",Released,A New Breed Of Secret Agent.,xXx,5.8,1424,7451,"[{""cast_id"": 8, ""character"": ""Xander Cage"", ""c...","[{""credit_id"": ""538d8c59c3a368714b004879"", ""de..."
4807,60000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/xxxstateoft...,11679,"[{""id"": 521, ""name"": ""washington d.c.""}, {""id""...",en,xXx: State of the Union,"Ice Cube stars as Darius Stone, a thrill-seeki...",36.689223,"[{""name"": ""Original Film"", ""id"": 333}, {""name""...",...,101.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Prepare for the next level,xXx: State of the Union,4.7,549,11679,"[{""cast_id"": 13, ""character"": ""Darius Stone / ...","[{""credit_id"": ""5578b667c3a3682a7500041a"", ""de..."
4808,62000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 878, ""na...",NaN,8202,"[{""id"": 779, ""name"": ""martial arts""}, {""id"": 4...",en,Ã†on Flux,"400 years into the future, disease has wiped o...",29.954302,"[{""name"": ""Paramount Pictures"", ""id"": 4}, {""na...",...,93.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Perfect World Meets The Perfect Assassin,Ã†on Flux,5.4,703,8202,"[{""cast_id"": 1, ""character"": ""Aeon Flux"", ""cre...","[{""credit_id"": ""52fe4495c3a36847f809e6f3"", ""de..."

In [6]:
movies.shape

(4803, 20)

In [7]:
credit.shape

(4803, 4)

In [8]:
df.shape

(4809, 23)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4809 entries, 0 to 4808
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4809 non-null   int64
 1   genres                4809 non-null   object
 2   homepage              1713 non-null   object
 3   id                    4809 non-null   int64
 4   keywords              4809 non-null   object
 5   original_language     4809 non-null   object
 6   original_title        4809 non-null   object
 7   overview              4806 non-null   object
 8   popularity            4809 non-null   float64
 9   production_companies  4809 non-null   object
 10  production_countries  4809 non-null   object
 11  release_date          4808 non-null   object
 12  revenue               4809 non-null   int64
 13  runtime               4807 non-null   float64
 14  spoken_languages      4809 non-null   object
 15  status                4809 non-null   object
 16  tagline               3965 non-null   object
 17  title                 4809 non-null   object
 18  vote_average          4809 non-null   float64
 19  vote_count            4809 non-null   int64
 20  movie_id              4809 non-null   int64
 21  cast                  4809 non-null   object
 22  crew                  4809 non-null   object
dtypes: float64(3), int64(5), object(15)
memory usage: 864.2+ KB

In [10]:
df.describe()

,budget,id,popularity,revenue,runtime,vote_average,vote_count,movie_id
count,4.809000e+03,4809.000000,4809.000000,4.809000e+03,4807.000000,4809.000000,4809.000000,4809.000000
mean,2.902780e+07,57120.571429,21.491664,8.227511e+07,106.882255,6.092514,690.331670,57120.571429
std,4.070473e+07,88653.369849,31.803366,1.628379e+08,22.602535,1.193989,1234.187111,88653.369849
min,0.000000e+00,5.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,5.000000
25%,7.800000e+05,9012.000000,4.667230,0.000000e+00,94.000000,5.600000,54.000000,9012.000000
50%,1.500000e+07,14624.000000,12.921594,1.917000e+07,103.000000,6.200000,235.000000,14624.000000
75%,4.000000e+07,58595.000000,28.350529,9.291317e+07,118.000000,6.800000,737.000000,58595.000000
max,3.800000e+08,459488.000000,875.581305,2.787965e+09,338.000000,10.000000,13752.000000,459488.000000

In [11]:
df.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count', 'movie_id', 'cast', 'crew'],
      dtype='object')

In [12]:
df = df[['movie_id',  'title', 'genres', 'keywords', 'overview', 'cast', 'crew']]

# Display the updated DataFrame
df.head()

,movie_id,title,genres,keywords,overview,cast,crew
0,301325,#Horror,"[{""id"": 18, ""name"": ""Drama""}, {""id"": 9648, ""na...",[],"Inspired by actual events, a group of 12 year ...","[{""cast_id"": 0, ""character"": ""Alex's 12-Step F...","[{""credit_id"": ""545bbac70e0a261fb6002329"", ""de..."
1,19913,(500) Days of Summer,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...","[{""id"": 248, ""name"": ""date""}, {""id"": 572, ""nam...","Tom (Joseph Gordon-Levitt), greeting-card writ...","[{""cast_id"": 4, ""character"": ""Tom Hansen"", ""cr...","[{""credit_id"": ""52fe47f99251416c750abaa5"", ""de..."
2,333371,10 Cloverfield Lane,"[{""id"": 53, ""name"": ""Thriller""}, {""id"": 878, ""...","[{""id"": 1930, ""name"": ""kidnapping""}, {""id"": 23...","After a car accident, Michelle awakens to find...","[{""cast_id"": 2, ""character"": ""Michelle"", ""cred...","[{""credit_id"": ""57627624c3a3680682000872"", ""de..."
3,345003,10 Days in a Madhouse,"[{""id"": 18, ""name"": ""Drama""}]","[{""id"": 1568, ""name"": ""undercover""}, {""id"": 49...","Nellie Bly, a 23 year-old reporter for Joseph ...","[{""cast_id"": 2, ""character"": ""Nellie Bly"", ""cr...","[{""credit_id"": ""594efa1fc3a36832650455ff"", ""de..."
4,4951,10 Things I Hate About You,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...","[{""id"": 497, ""name"": ""shakespeare""}, {""id"": 59...","Bianca, a tenth grader, has never gone on a da...","[{""cast_id"": 2, ""character"": ""Patrick Verona"",...","[{""credit_id"": ""52fe43e6c3a36847f807731d"", ""de..."

In [13]:
df.isnull().sum()

movie_id    0
title       0
genres      0
keywords    0
overview    3
cast        0
crew        0
dtype: int64

In [14]:
df.dropna(inplace=True)

In [15]:
df.head(15)

,movie_id,title,genres,keywords,overview,cast,crew
0,301325,#Horror,"[{""id"": 18, ""name"": ""Drama""}, {""id"": 9648, ""na...",[],"Inspired by actual events, a group of 12 year ...","[{""cast_id"": 0, ""character"": ""Alex's 12-Step F...","[{""credit_id"": ""545bbac70e0a261fb6002329"", ""de..."
1,19913,(500) Days of Summer,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...","[{""id"": 248, ""name"": ""date""}, {""id"": 572, ""nam...","Tom (Joseph Gordon-Levitt), greeting-card writ...","[{""cast_id"": 4, ""character"": ""Tom Hansen"", ""cr...","[{""credit_id"": ""52fe47f99251416c750abaa5"", ""de..."
2,333371,10 Cloverfield Lane,"[{""id"": 53, ""name"": ""Thriller""}, {""id"": 878, ""...","[{""id"": 1930, ""name"": ""kidnapping""}, {""id"": 23...","After a car accident, Michelle awakens to find...","[{""cast_id"": 2, ""character"": ""Michelle"", ""cred...","[{""credit_id"": ""57627624c3a3680682000872"", ""de..."
3,345003,10 Days in a Madhouse,"[{""id"": 18, ""name"": ""Drama""}]","[{""id"": 1568, ""name"": ""undercover""}, {""id"": 49...","Nellie Bly, a 23 year-old reporter for Joseph ...","[{""cast_id"": 2, ""character"": ""Nellie Bly"", ""cr...","[{""credit_id"": ""594efa1fc3a36832650455ff"", ""de..."
4,4951,10 Things I Hate About You,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...","[{""id"": 497, ""name"": ""shakespeare""}, {""id"": 59...","Bianca, a tenth grader, has never gone on a da...","[{""cast_id"": 2, ""character"": ""Patrick Verona"",...","[{""credit_id"": ""52fe43e6c3a36847f807731d"", ""de..."
5,10481,102 Dalmatians,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10751, ""...","[{""id"": 212, ""name"": ""london england""}, {""id"":...",Get ready for a howling good time as an all ne...,"[{""cast_id"": 1, ""character"": ""Cruella de Vil"",...","[{""credit_id"": ""5539fe5e9251413f5a00359b"", ""de..."
6,13197,10th & Wolf,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 1568, ""name"": ""undercover""}, {""id"": 10...",A former street tough returns to his Philadelp...,"[{""cast_id"": 1, ""character"": ""Tommy"", ""credit_...","[{""credit_id"": ""52fe454d9251416c75051e59"", ""de..."
7,9282,11:14,"[{""id"": 80, ""name"": ""Crime""}, {""id"": 18, ""name...","[{""id"": 567, ""name"": ""alcohol""}, {""id"": 572, ""...",Tells the seemingly random yet vitally connect...,"[{""cast_id"": 10, ""character"": ""Jack"", ""credit_...","[{""credit_id"": ""52fe44e1c3a36847f80af88d"", ""de..."
8,389,12 Angry Men,"[{""id"": 18, ""name"": ""Drama""}]","[{""id"": 934, ""name"": ""judge""}, {""id"": 1417, ""n...",The defense and the prosecution have rested an...,"[{""cast_id"": 29, ""character"": ""Juror 8"", ""cred...","[{""credit_id"": ""52fe423dc3a36847f800ec55"", ""de..."
9,17134,12 Rounds,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 6149, ""name"": ""police""}, {""id"": 8233, ...",When New Orleans cop Danny Fisher prevents a b...,"[{""cast_id"": 1, ""character"": ""Det. Danny Fishe...","[{""credit_id"": ""538ee0730e0a2644b9001141"", ""de..."
10,76203,12 Years a Slave,"[{""id"": 18, ""name"": ""Drama""}, {""id"": 36, ""name...","[{""id"": 1294, ""name"": ""whip""}, {""id"": 1930, ""n...","In the pre-Civil War United States, Solomon No...","[{""cast_id"": 6, ""character"": ""Solomon Northup""...","[{""credit_id"": ""52fe492cc3a368484e11dfdb"", ""de..."
11,44115,127 Hours,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 18, ""...","[{""id"": 1262, ""name"": ""mountains""}, {""id"": 230...",The true story of mountain climber Aron Ralsto...,"[{""cast_id"": 2, ""character"": ""Aron Ralston"", ""...","[{""credit_id"": ""52fe4677c3a36847f8100b31"", ""de..."
12,10096,13 Going on 30,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 14, ""nam...","[{""id"": 242, ""name"": ""new york""}, {""id"": 1003,...",After total humiliation at her thirteenth birt...,"[{""cast_id"": 12, ""character"": ""Jenna Rink"", ""c...","[{""credit_id"": ""52fe43259251416c750054a3"", ""de..."
13,300671,13 Hours: The Secret Soldiers of Benghazi,"[{""id"": 28, ""name"": ""Action""}, {""id"": 18, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",An American Ambassador is killed during an att...,"[{""cast_id"": 2, ""character"": ""Tyrone 'Rone' Wo...","[{""credit_id"": ""56c5a7cdc3a3680d3e002ae4"", ""de..."
14,3021,1408,"[{""id"": 27, ""name"": ""Horror""}, {""id"": 53, ""nam...","[{""id"": 236, ""name"": ""suicide""}, {""id"": 242, ""...",A man who specializes in debunking paranormal ...,"[{""cast_id"": 19, ""character"": ""Mike Enslin"", ""...","[{""credit_id"": ""52fe437dc3a36847f8057f15"", ""de..."

In [16]:
df.duplicated().sum()

0

# MODEL BUILDING

In [17]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [18]:
import ast 

def convert(obj):
    L=[]
    for i in ast.literal_eval(obj):
        L.append(i['name'])
    return L

In [19]:
df['genres']=df['genres'].apply(convert)

In [20]:
df.head()

,movie_id,title,genres,keywords,overview,cast,crew
0,301325,#Horror,"[Drama, Mystery, Horror, Thriller]",[],"Inspired by actual events, a group of 12 year ...","[{""cast_id"": 0, ""character"": ""Alex's 12-Step F...","[{""credit_id"": ""545bbac70e0a261fb6002329"", ""de..."
1,19913,(500) Days of Summer,"[Comedy, Drama, Romance]","[{""id"": 248, ""name"": ""date""}, {""id"": 572, ""nam...","Tom (Joseph Gordon-Levitt), greeting-card writ...","[{""cast_id"": 4, ""character"": ""Tom Hansen"", ""cr...","[{""credit_id"": ""52fe47f99251416c750abaa5"", ""de..."
2,333371,10 Cloverfield Lane,"[Thriller, Science Fiction, Drama]","[{""id"": 1930, ""name"": ""kidnapping""}, {""id"": 23...","After a car accident, Michelle awakens to find...","[{""cast_id"": 2, ""character"": ""Michelle"", ""cred...","[{""credit_id"": ""57627624c3a3680682000872"", ""de..."
3,345003,10 Days in a Madhouse,[Drama],"[{""id"": 1568, ""name"": ""undercover""}, {""id"": 49...","Nellie Bly, a 23 year-old reporter for Joseph ...","[{""cast_id"": 2, ""character"": ""Nellie Bly"", ""cr...","[{""credit_id"": ""594efa1fc3a36832650455ff"", ""de..."
4,4951,10 Things I Hate About You,"[Comedy, Romance, Drama]","[{""id"": 497, ""name"": ""shakespeare""}, {""id"": 59...","Bianca, a tenth grader, has never gone on a da...","[{""cast_id"": 2, ""character"": ""Patrick Verona"",...","[{""credit_id"": ""52fe43e6c3a36847f807731d"", ""de..."

In [21]:
df['keywords']=df['keywords'].apply(convert)

In [22]:
import ast

def convert3(obj):
    L = []  # Initialize an empty list
    counter = 0  # Initialize counter

    for i in ast.literal_eval(obj):  # Safely evaluate the string as a Python object
        if counter != 3:
            L.append(i['name'])  # Append the 'name' value to the list
            counter += 1  # Increment counter
        else:
            break  # Exit loop after 3 elements
    
    return L  # Return the list

In [23]:
df['cast']=df['cast'].apply(convert3)

In [24]:
import ast

def fetch_director(obj):
    L = []  # Initialize an empty list
    
    for i in ast.literal_eval(obj):  # Convert string representation to a list of dictionaries
        if i['job'] == 'Director':  # Check if the job is 'Director'
            L.append(i['name'])  # Append director's name to the list
            break  # Stop after finding the first director
    
    return L  # Return the list

In [25]:
df['crew']=df['crew'].apply(fetch_director)

In [26]:
df.head()

,movie_id,title,genres,keywords,overview,cast,crew
0,301325,#Horror,"[Drama, Mystery, Horror, Thriller]",[],"Inspired by actual events, a group of 12 year ...","[Taryn Manning, Natasha Lyonne, ChloÃ« Sevigny]",[Tara Subkoff]
1,19913,(500) Days of Summer,"[Comedy, Drama, Romance]","[date, sex, jealousy, fight, architect, galler...","Tom (Joseph Gordon-Levitt), greeting-card writ...","[Joseph Gordon-Levitt, Zooey Deschanel, ChloÃ« ...",[Marc Webb]
2,333371,10 Cloverfield Lane,"[Thriller, Science Fiction, Drama]","[kidnapping, bunker, paranoia, basement, survi...","After a car accident, Michelle awakens to find...","[Mary Elizabeth Winstead, John Goodman, John G...",[Dan Trachtenberg]
3,345003,10 Days in a Madhouse,[Drama],"[undercover, insane asylum, reporter]","Nellie Bly, a 23 year-old reporter for Joseph ...","[Caroline Barry, Christopher Lambert, Kelly Le...",[Timothy Hines]
4,4951,10 Things I Hate About You,"[Comedy, Romance, Drama]","[shakespeare, sister, high school, cannabis, d...","Bianca, a tenth grader, has never gone on a da...","[Heath Ledger, Julia Stiles, Joseph Gordon-Lev...",[Gil Junger]

In [27]:
df['overview']=df['overview'].apply(lambda x:x.split())

In [28]:
df.head()

,movie_id,title,genres,keywords,overview,cast,crew
0,301325,#Horror,"[Drama, Mystery, Horror, Thriller]",[],"[Inspired, by, actual, events,, a, group, of, ...","[Taryn Manning, Natasha Lyonne, ChloÃ« Sevigny]",[Tara Subkoff]
1,19913,(500) Days of Summer,"[Comedy, Drama, Romance]","[date, sex, jealousy, fight, architect, galler...","[Tom, (Joseph, Gordon-Levitt),, greeting-card,...","[Joseph Gordon-Levitt, Zooey Deschanel, ChloÃ« ...",[Marc Webb]
2,333371,10 Cloverfield Lane,"[Thriller, Science Fiction, Drama]","[kidnapping, bunker, paranoia, basement, survi...","[After, a, car, accident,, Michelle, awakens, ...","[Mary Elizabeth Winstead, John Goodman, John G...",[Dan Trachtenberg]
3,345003,10 Days in a Madhouse,[Drama],"[undercover, insane asylum, reporter]","[Nellie, Bly,, a, 23, year-old, reporter, for,...","[Caroline Barry, Christopher Lambert, Kelly Le...",[Timothy Hines]
4,4951,10 Things I Hate About You,"[Comedy, Romance, Drama]","[shakespeare, sister, high school, cannabis, d...","[Bianca,, a, tenth, grader,, has, never, gone,...","[Heath Ledger, Julia Stiles, Joseph Gordon-Lev...",[Gil Junger]

In [29]:
df['genres'] = df['genres'].apply(lambda x: [i.replace(" ", "") for i in x])
df['keywords'] = df['keywords'].apply(lambda x: [i.replace(" ", "") for i in x])
df['cast'] = df['cast'].apply(lambda x: [i.replace(" ", "") for i in x])
df['crew'] = df['crew'].apply(lambda x: [i.replace(" ", "") for i in x])

In [30]:
df['Tags']=df['genres']+df['keywords']++df['cast']+df['crew']

In [31]:
df.head()

,movie_id,title,genres,keywords,overview,cast,crew,Tags
0,301325,#Horror,"[Drama, Mystery, Horror, Thriller]",[],"[Inspired, by, actual, events,, a, group, of, ...","[TarynManning, NatashaLyonne, ChloÃ«Sevigny]",[TaraSubkoff],"[Drama, Mystery, Horror, Thriller, TarynMannin..."
1,19913,(500) Days of Summer,"[Comedy, Drama, Romance]","[date, sex, jealousy, fight, architect, galler...","[Tom, (Joseph, Gordon-Levitt),, greeting-card,...","[JosephGordon-Levitt, ZooeyDeschanel, ChloÃ«Gra...",[MarcWebb],"[Comedy, Drama, Romance, date, sex, jealousy, ..."
2,333371,10 Cloverfield Lane,"[Thriller, ScienceFiction, Drama]","[kidnapping, bunker, paranoia, basement, survi...","[After, a, car, accident,, Michelle, awakens, ...","[MaryElizabethWinstead, JohnGoodman, JohnGalla...",[DanTrachtenberg],"[Thriller, ScienceFiction, Drama, kidnapping, ..."
3,345003,10 Days in a Madhouse,[Drama],"[undercover, insaneasylum, reporter]","[Nellie, Bly,, a, 23, year-old, reporter, for,...","[CarolineBarry, ChristopherLambert, KellyLeBrock]",[TimothyHines],"[Drama, undercover, insaneasylum, reporter, Ca..."
4,4951,10 Things I Hate About You,"[Comedy, Romance, Drama]","[shakespeare, sister, highschool, cannabis, de...","[Bianca,, a, tenth, grader,, has, never, gone,...","[HeathLedger, JuliaStiles, JosephGordon-Levitt]",[GilJunger],"[Comedy, Romance, Drama, shakespeare, sister, ..."

In [32]:
new_df= df[['movie_id',"title","Tags"]]
new_df

,movie_id,title,Tags
0,301325,#Horror,"[Drama, Mystery, Horror, Thriller, TarynMannin..."
1,19913,(500) Days of Summer,"[Comedy, Drama, Romance, date, sex, jealousy, ..."
2,333371,10 Cloverfield Lane,"[Thriller, ScienceFiction, Drama, kidnapping, ..."
3,345003,10 Days in a Madhouse,"[Drama, undercover, insaneasylum, reporter, Ca..."
4,4951,10 Things I Hate About You,"[Comedy, Romance, Drama, shakespeare, sister, ..."
...,...,...,...
4804,10664,[REC]Â²,"[Thriller, Horror, religionandsupernatural, bl..."
4805,1946,eXistenZ,"[Action, Thriller, ScienceFiction, Horror, vid..."
4806,7451,xXx,"[Action, Adventure, Thriller, sportscar, biolo..."
4807,11679,xXx: State of the Union,"[Action, Adventure, Crime, Drama, Mystery, Thr..."
4808,8202,Ã†on Flux,"[Action, ScienceFiction, martialarts, dystopia..."

In [33]:
new_df['Tags']=new_df['Tags'].apply(lambda x: " ".join(x))

In [34]:
new_df.head()

,movie_id,title,Tags
0,301325,#Horror,Drama Mystery Horror Thriller TarynManning Nat...
1,19913,(500) Days of Summer,Comedy Drama Romance date sex jealousy fight a...
2,333371,10 Cloverfield Lane,Thriller ScienceFiction Drama kidnapping bunke...
3,345003,10 Days in a Madhouse,Drama undercover insaneasylum reporter Carolin...
4,4951,10 Things I Hate About You,Comedy Romance Drama shakespeare sister highsc...

In [35]:
new_df['Tags']=new_df['Tags'].apply(lambda x: x.lower())

In [36]:
new_df.head()

,movie_id,title,Tags
0,301325,#Horror,drama mystery horror thriller tarynmanning nat...
1,19913,(500) Days of Summer,comedy drama romance date sex jealousy fight a...
2,333371,10 Cloverfield Lane,thriller sciencefiction drama kidnapping bunke...
3,345003,10 Days in a Madhouse,drama undercover insaneasylum reporter carolin...
4,4951,10 Things I Hate About You,comedy romance drama shakespeare sister highsc...

In [37]:
new_df['Tags'][0]

'drama mystery horror thriller tarynmanning natashalyonne chloÃ«sevigny tarasubkoff'

In [38]:
new_df['Tags'][1]

'comedy drama romance date sex jealousy fight architect gallery interview sister party love friends fate losangeles summer ikea year heartache josephgordon-levitt zooeydeschanel chloÃ«gracemoretz marcwebb'

In [39]:
from sklearn.feature_extraction.text import CountVectorizer

# Initialize CountVectorizer with max features and stop words
cv = CountVectorizer(max_features=5000, stop_words='english')

# Convert 'tags' column into a matrix of token counts
vectors = cv.fit_transform(new_df['Tags']).toarray()

In [40]:
vectors[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [41]:
cv.get_feature_names_out()

array(['16thcentury', '17thcentury', '18thcentury', ..., 'zoo',
       'zooeydeschanel', 'zoÃ«kravitz'], dtype=object)

In [42]:
import nltk
from nltk.stem.porter import PorterStemmer

# Initialize PorterStemmer
ps = PorterStemmer()

In [43]:
ps.stem("loving")

'love'

In [44]:
def stem(text):
    y=[]
    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)

In [45]:
new_df['Tags']=new_df['Tags'].apply(stem)

In [46]:
new_df.head()

,movie_id,title,Tags
0,301325,#Horror,drama mysteri horror thriller tarynman natasha...
1,19913,(500) Days of Summer,comedi drama romanc date sex jealousi fight ar...
2,333371,10 Cloverfield Lane,thriller sciencefict drama kidnap bunker paran...
3,345003,10 Days in a Madhouse,drama undercov insaneasylum report carolinebar...
4,4951,10 Things I Hate About You,comedi romanc drama shakespear sister highscho...

In [47]:
from sklearn.metrics.pairwise import cosine_similarity

# Compute cosine similarity between vectors
similarity = cosine_similarity(vectors)

# Accessing similarity for index 2
print(similarity[2])

# Accessing similarity for index 0
print(similarity[0])

[0.21821789 0.06154575 1.         ... 0.07715167 0.13608276 0.07216878]
[1.         0.0805823  0.21821789 ... 0.10101525 0.26726124 0.        ]

In [48]:
sorted(similarity[0],reverse=True)

[0.9999999999999998,
 0.6761234037828132,
 0.6546536707079772,
 0.5714285714285713,
 0.5714285714285713,
 0.5669467095138407,
 0.5669467095138407,
 0.5669467095138407,
 0.5669467095138407,
 0.5669467095138407,
 0.5345224838248487,
 0.5345224838248487,
 0.5345224838248487,
 0.50709255283711,
 0.50709255283711,
 0.50709255283711,
 0.50709255283711,
 0.50709255283711,
 0.5039526306789696,
 0.4629100498862757,
 0.4629100498862757,
 0.4629100498862757,
 0.4629100498862757,
 0.4629100498862757,
 0.4629100498862757,
 0.4629100498862757,
 0.4558423058385518,
 0.4558423058385518,
 0.4558423058385518,
 0.4558423058385518,
 0.4364357804719848,
 0.4364357804719848,
 0.4364357804719848,
 0.4364357804719848,
 0.4364357804719848,
 0.4364357804719848,
 0.4364357804719848,
 0.4364357804719848,
 0.4364357804719848,
 0.4364357804719848,
 0.4364357804719848,
 0.4364357804719848,
 0.4364357804719848,
 0.4364357804719848,
 0.4364357804719848,
 0.4364357804719848,
 0.4364357804719848,
 0.4364357804719848,
 0.4364357804719848,
 0.4364357804719848,
 0.4364357804719848,
 0.4364357804719848,
 0.4364357804719848,
 0.4364357804719848,
 0.4364357804719848,
 0.4364357804719848,
 0.4285714285714285,
 0.4285714285714285,
 0.4285714285714285,
 0.4285714285714285,
 0.4285714285714285,
 0.4285714285714285,
 0.4285714285714285,
 0.4285714285714285,
 0.4285714285714285,
 0.40089186286863654,
 0.40089186286863654,
 0.40089186286863654,
 0.40089186286863654,
 0.40089186286863654,
 0.40089186286863654,
 0.40089186286863654,
 0.40089186286863654,
 0.40089186286863654,
 0.40089186286863654,
 0.40089186286863654,
 0.40089186286863654,
 0.40089186286863654,
 0.3903600291794132,
 0.3779644730092272,
 0.3779644730092272,
 0.3779644730092272,
 0.3779644730092272,
 0.3779644730092272,
 0.3779644730092272,
 0.3779644730092272,
 0.3779644730092272,
 0.3779644730092272,
 0.3779644730092272,
 0.3779644730092272,
 0.3779644730092272,
 0.3779644730092272,
 0.3779644730092272,
 0.3779644730092272,
 0.3779644730092272,
 0.3779644730092272,
 0.3779644730092272,
 0.3779644730092272,
 0.3779644730092272,
 0.3779644730092272,
 0.3779644730092272,
 0.3779644730092272,
 0.3779644730092272,
 0.3779644730092272,
 0.3779644730092272,
 0.3779644730092272,
 0.3779644730092272,
 0.3779644730092272,
 0.3779644730092272,
 0.3779644730092272,
 0.3779644730092272,
 0.3779644730092272,
 0.3779644730092272,
 0.3779644730092272,
 0.3779644730092272,
 0.3779644730092272,
 0.3779644730092272,
 0.3779644730092272,
 0.3779644730092272,
 0.3779644730092272,
 0.3779644730092272,
 0.3779644730092272,
 0.3779644730092272,
 0.3779644730092272,
 0.3779644730092272,
 0.3779644730092272,
 0.3779644730092272,
 0.3779644730092272,
 0.3779644730092272,
 0.3779644730092272,
 0.3779644730092272,
 0.3779644730092272,
 0.3779644730092272,
 0.3779644730092272,
 0.3779644730092272,
 0.3779644730092272,
 0.3779644730092272,
 0.3779644730092272,
 0.3779644730092272,
 0.3666793988112845,
 0.3585685828003181,
 0.3585685828003181,
 0.3585685828003181,
 0.3585685828003181,
 0.3585685828003181,
 0.3585685828003181,
 0.3585685828003181,
 0.3585685828003181,
 0.3585685828003181,
 0.3585685828003181,
 0.3585685828003181,
 0.3585685828003181,
 0.3585685828003181,
 0.3585685828003181,
 0.3585685828003181,
 0.3585685828003181,
 0.3468439878096479,
 0.3418817293789138,
 0.3418817293789138,
 0.3418817293789138,
 0.3418817293789138,
 0.3418817293789138,
 0.3418817293789138,
 0.3418817293789138,
 0.3418817293789138,
 0.3418817293789138,
 0.3418817293789138,
 0.3418817293789138,
 0.3418817293789138,
 0.3418817293789138,
 0.3418817293789138,
 0.3418817293789138,
 0.3418817293789138,
 0.3418817293789138,
 0.3418817293789138,
 0.3418817293789138,
 0.3380617018914066,
 0.3380617018914066,
 0.3380617018914066,
 0.3380617018914066,
 0.3380617018914066,
 0.3380617018914066,
 0.3380617018914066,
 0.3380617018914066,
 0.3380617018914066,
 0.3380617018914066,
 0.3380617018914066,
 0.3380617018914066,
 0.3380617018914066,
 0.3380617018914066,
 0.3380617018914066,
 0.3380617018914066,
 0.3380617018914066,
 0.3380617018914066,
 0.3380617018914066,
 0.3380617018914066,
 0.3380617018914066,
 0.3380617018914066,
 0.3380617018914066,
 0.3380617018914066,
 0.3380617018914066,
 0.3380617018914066,
 0.3380617018914066,
 0.3380617018914066,
 0.3380617018914066,
 0.3380617018914066,
 0.3380617018914066,
 0.329914439536929,
 0.3273268353539886,
 0.3273268353539886,
 0.3273268353539886,
 0.3273268353539886,
 0.3273268353539886,
 0.3273268353539886,
 0.3273268353539886,
 0.3273268353539886,
 0.3273268353539886,
 0.3273268353539886,
 0.3273268353539886,
 0.3273268353539886,
 0.3273268353539886,
 0.3273268353539886,
 0.3273268353539886,
 0.3273268353539886,
 0.3273268353539886,
 0.3273268353539886,
 0.3273268353539886,
 0.3144854510165755,
 0.3144854510165755,
 0.3144854510165755,
 0.3144854510165755,
 0.3144854510165755,
 0.3144854510165755,
 0.3144854510165755,
 0.3144854510165755,
 0.3144854510165755,
 0.3144854510165755,
 0.3144854510165755,
 0.3144854510165755,
 0.3086066999241838,
 0.3086066999241838,
 0.3086066999241838,
 0.3086066999241838,
 0.3086066999241838,
 0.3086066999241838,
 0.3086066999241838,
 0.3086066999241838,
 0.3086066999241838,
 0.3086066999241838,
 0.3086066999241838,
 0.3086066999241838,
 0.3086066999241838,
 0.3086066999241838,
 0.3086066999241838,
 0.3086066999241838,
 0.3086066999241838,
 0.3086066999241838,
 0.3086066999241838,
 0.3086066999241838,
 0.3086066999241838,
 0.3086066999241838,
 0.3086066999241838,
 0.3086066999241838,
 0.3086066999241838,
 0.3086066999241838,
 0.3086066999241838,
 0.3086066999241838,
 0.3086066999241838,
 0.3086066999241838,
 0.3086066999241838,
 0.3086066999241838,
 0.3030457633656632,
 0.3030457633656632,
 0.3030457633656632,
 0.3030457633656632,
 0.3030457633656632,
 0.3030457633656632,
 0.3030457633656632,
 0.3030457633656632,
 0.3030457633656632,
 0.2927700218845599,
 0.2927700218845599,
 0.2927700218845599,
 0.2927700218845599,
 0.2927700218845599,
 0.2927700218845599,
 0.2927700218845599,
 0.2927700218845599,
 0.2927700218845599,
 0.2927700218845599,
 0.2927700218845599,
 0.28571428571428564,
 0.28571428571428564,
 0.28571428571428564,
 0.28571428571428564,
 0.28571428571428564,
 0.28571428571428564,
 0.28571428571428564,
 0.28571428571428564,
 0.28571428571428564,
 0.28571428571428564,
 0.28571428571428564,
 0.28571428571428564,
 0.28571428571428564,
 0.28571428571428564,
 0.28571428571428564,
 0.28571428571428564,
 0.28571428571428564,
 0.28571428571428564,
 0.28571428571428564,
 0.28571428571428564,
 0.28571428571428564,
 0.28571428571428564,
 0.28571428571428564,
 0.28571428571428564,
 0.28571428571428564,
 0.28571428571428564,
 0.28571428571428564,
 0.28571428571428564,
 0.28571428571428564,
 0.28571428571428564,
 0.28571428571428564,
 0.28571428571428564,
 0.28571428571428564,
 0.28571428571428564,
 0.28571428571428564,
 0.28571428571428564,
 0.28571428571428564,
 0.28571428571428564,
 0.28571428571428564,
 0.28571428571428564,
 0.28347335475692037,
 0.28347335475692037,
 0.28347335475692037,
 0.28347335475692037,
 0.28347335475692037,
 0.28347335475692037,
 0.28347335475692037,
 0.28347335475692037,
 0.28347335475692037,
 0.28347335475692037,
 0.28347335475692037,
 0.28347335475692037,
 0.28347335475692037,
 0.28347335475692037,
 0.28347335475692037,
 0.28347335475692037,
 0.27500954910846337,
 0.27500954910846337,
 0.27500954910846337,
 0.27500954910846337,
 0.27500954910846337,
 0.27500954910846337,
 0.27500954910846337,
 0.27500954910846337,
 0.27500954910846337,
 0.27500954910846337,
 0.27500954910846337,
 0.27153769332085226,
 0.2672612419124244,
 0.2672612419124244,
 0.2672612419124244,
 0.2672612419124244,
 0.2672612419124244,
 0.26726124191242434,
 0.26726124191242434,
 0.26726124191242434,
 0.26726124191242434,
 0.26726124191242434,
 0.26726124191242434,
 0.26726124191242434,
 0.26726124191242434,
 0.26726124191242434,
 0.26726124191242434,
 0.26726124191242434,
 0.26726124191242434,
 0.26726124191242434,
 0.26726124191242434,
 0.26726124191242434,
 0.26726124191242434,
 0.26726124191242434,
 0.26726124191242434,
 0.26726124191242434,
 0.26726124191242434,
 0.26726124191242434,
 0.26726124191242434,
 0.26726124191242434,
 0.26726124191242434,
 0.26726124191242434,
 0.26726124191242434,
 0.26726124191242434,
 0.26726124191242434,
 0.26726124191242434,
 0.26726124191242434,
 0.26726124191242434,
 0.26726124191242434,
 0.26726124191242434,
 0.26726124191242434,
 0.26726124191242434,
 0.26726124191242434,
 0.26726124191242434,
 0.26726124191242434,
 0.26726124191242434,
 0.26726124191242434,
 0.26726124191242434,
 0.26726124191242434,
 0.26726124191242434,
 0.26726124191242434,
 0.26726124191242434,
 0.26726124191242434,
 0.26726124191242434,
 0.26726124191242434,
 0.26726124191242434,
 0.26726124191242434,
 0.26726124191242434,
 0.26726124191242434,
 0.26726124191242434,
 0.26726124191242434,
 0.26726124191242434,
 0.26726124191242434,
 0.26726124191242434,
 0.26726124191242434,
 0.26726124191242434,
 0.26726124191242434,
 0.26726124191242434,
 0.26726124191242434,
 0.26726124191242434,
 0.26726124191242434,
 0.26726124191242434,
 0.26726124191242434,
 0.26726124191242434,
 0.26726124191242434,
 0.26726124191242434,
 0.26726124191242434,
 0.26726124191242434,
 0.26726124191242434,
 0.26726124191242434,
 0.26726124191242434,
 0.26726124191242434,
 0.26726124191242434,
 0.26726124191242434,
 0.26726124191242434,
 0.26726124191242434,
 0.26726124191242434,
 0.26726124191242434,
 0.26726124191242434,
 0.26726124191242434,
 0.26726124191242434,
 0.26726124191242434,
 0.26726124191242434,
 0.26726124191242434,
 0.26726124191242434,
 0.26013299085723596,
 0.26013299085723596,
 0.253546276418555,
 0.253546276418555,
 0.253546276418555,
 0.253546276418555,
 0.253546276418555,
 0.2519763153394848,
 0.2519763153394848,
 0.2519763153394848,
 0.2519763153394848,
 0.2519763153394848,
 0.2519763153394848,
 0.2519763153394848,
 0.2519763153394848,
 0.2519763153394848,
 0.2519763153394848,
 0.2519763153394848,
 0.2519763153394848,
 0.2519763153394848,
 0.2519763153394848,
 0.2519763153394848,
 0.2519763153394848,
 0.2519763153394848,
 0.2519763153394848,
 0.2519763153394848,
 0.2519763153394848,
 0.2519763153394848,
 0.2519763153394848,
 0.2519763153394848,
 0.2519763153394848,
 0.2519763153394848,
 0.2519763153394848,
 0.2519763153394848,
 0.2519763153394848,
 0.2519763153394848,
 0.2519763153394848,
 0.2519763153394848,
 0.2519763153394848,
 0.2519763153394848,
 0.2519763153394848,
 0.2519763153394848,
 0.2519763153394848,
 0.2519763153394848,
 0.2519763153394848,
 0.2519763153394848,
 0.2519763153394848,
 0.2519763153394848,
 0.2519763153394848,
 0.2519763153394848,
 0.2519763153394848,
 0.2519763153394848,
 0.2519763153394848,
 0.2519763153394848,
 0.2519763153394848,
 0.2519763153394848,
 0.2519763153394848,
 0.2519763153394848,
 0.2519763153394848,
 0.2519763153394848,
 0.2519763153394848,
 0.2519763153394848,
 0.2519763153394848,
 0.24743582965269675,
 0.24743582965269675,
 0.24743582965269675,
 0.24174688920761406,
 0.24174688920761406,
 0.24174688920761406,
 0.24174688920761406,
 0.24174688920761406,
 0.24174688920761406,
 0.23904572186687872,
 0.23904572186687872,
 0.23904572186687872,
 0.23904572186687872,
 0.23904572186687872,
 0.23904572186687872,
 0.23904572186687872,
 0.23904572186687872,
 0.23904572186687872,
 0.23904572186687872,
 0.23904572186687872,
 0.23904572186687872,
 0.23904572186687872,
 0.23904572186687872,
 0.23904572186687872,
 0.23904572186687872,
 0.23904572186687872,
 0.23904572186687872,
 0.23904572186687872,
 0.23904572186687872,
 0.23904572186687872,
 0.23904572186687872,
 0.23904572186687872,
 0.23904572186687872,
 0.23904572186687872,
 0.23904572186687872,
 0.23904572186687872,
 0.23904572186687872,
 0.23904572186687872,
 0.23904572186687872,
 0.23904572186687872,
 0.23904572186687872,
 0.23904572186687872,
 0.23904572186687872,
 0.23904572186687872,
 0.23904572186687872,
 0.23904572186687872,
 0.23904572186687872,
 0.23904572186687872,
 0.23904572186687872,
 0.23904572186687872,
 0.23904572186687872,
 0.23904572186687872,
 0.23904572186687872,
 0.23904572186687872,
 0.23904572186687872,
 0.23904572186687872,
 0.23904572186687872,
 0.23904572186687872,
 0.23904572186687872,
 0.23904572186687872,
 0.23904572186687872,
 0.23904572186687872,
 0.23904572186687872,
 0.23904572186687872,
 0.23904572186687872,
 0.23904572186687872,
 0.23904572186687872,
 0.23904572186687872,
 0.23904572186687872,
 0.23904572186687872,
 0.23904572186687872,
 0.23904572186687872,
 0.23904572186687872,
 0.23904572186687872,
 0.23904572186687872,
 0.23904572186687872,
 0.23643312187173018,
 0.23643312187173018,
 0.23643312187173018,
 0.23643312187173018,
 0.23643312187173018,
 0.23145502494313785,
 0.23145502494313785,
 0.2279211529192759,
 0.2279211529192759,
 0.2279211529192759,
 0.2279211529192759,
 0.2279211529192759,
 0.2279211529192759,
 0.2279211529192759,
 0.2279211529192759,
 0.2279211529192759,
 0.2279211529192759,
 0.2279211529192759,
 0.2279211529192759,
 0.2279211529192759,
 0.2279211529192759,
 0.2279211529192759,
 0.2279211529192759,
 0.2279211529192759,
 0.2279211529192759,
 0.2279211529192759,
 0.2279211529192759,
 0.2279211529192759,
 0.2279211529192759,
 0.2279211529192759,
 0.2279211529192759,
 0.2279211529192759,
 0.2279211529192759,
 0.2279211529192759,
 0.2279211529192759,
 0.2279211529192759,
 0.2279211529192759,
 0.2279211529192759,
 0.2279211529192759,
 0.2279211529192759,
 0.2279211529192759,
 0.2279211529192759,
 0.2279211529192759,
 0.2279211529192759,
 0.2279211529192759,
 0.2279211529192759,
 0.2279211529192759,
 0.2279211529192759,
 0.2279211529192759,
 0.2279211529192759,
 0.2279211529192759,
 0.2279211529192759,
 0.2279211529192759,
 0.2279211529192759,
 0.2279211529192759,
 0.2279211529192759,
 0.2279211529192759,
 0.2279211529192759,
 0.2279211529192759,
 0.2279211529192759,
 0.2279211529192759,
 0.2279211529192759,
 0.2279211529192759,
 0.2279211529192759,
 0.2279211529192759,
 0.2279211529192759,
 0.2279211529192759,
 0.2279211529192759,
 0.2279211529192759,
 0.2279211529192759,
 0.2279211529192759,
 0.2279211529192759,
 0.22677868380553634,
 0.22677868380553634,
 0.2182178902359924,
 0.2182178902359924,
 0.2182178902359924,
 0.2182178902359924,
 0.2182178902359924,
 0.2182178902359924,
 0.2182178902359924,
 0.2182178902359924,
 0.2182178902359924,
 0.2182178902359924,
 0.2182178902359924,
 0.2182178902359924,
 0.2182178902359924,
 0.2182178902359924,
 0.2182178902359924,
 0.2182178902359924,
 0.2182178902359924,
 0.2182178902359924,
 0.2182178902359924,
 0.2182178902359924,
 0.2182178902359924,
 0.2182178902359924,
 0.2182178902359924,
 0.2182178902359924,
 0.2182178902359924,
 0.2182178902359924,
 0.2182178902359924,
 0.2182178902359924,
 0.2182178902359924,
 0.2182178902359924,
 0.2182178902359924,
 0.2182178902359924,
 0.2182178902359924,
 0.2182178902359924,
 0.2182178902359924,
 0.2182178902359924,
 0.2182178902359924,
 0.2182178902359924,
 0.2182178902359924,
 0.2182178902359924,
 0.2182178902359924,
 0.2182178902359924,
 0.2182178902359924,
 0.2182178902359924,
 0.2182178902359924,
 0.2182178902359924,
 0.2182178902359924,
 0.2182178902359924,
 0.2182178902359924,
 0.2182178902359924,
 0.2182178902359924,
 0.2182178902359924,
 0.2182178902359924,
 0.2182178902359924,
 0.2182178902359924,
 0.2182178902359924,
 0.2182178902359924,
 0.2182178902359924,
 0.2182178902359924,
 0.2182178902359924,
 0.2182178902359924,
 0.2182178902359924,
 0.2182178902359924,
 0.2182178902359924,
 0.2182178902359924,
 0.2182178902359924,
 0.2182178902359924,
 0.2182178902359924,
 0.2182178902359924,
 0.2182178902359924,
 0.2182178902359924,
 0.2182178902359924,
 0.2182178902359924,
 0.2182178902359924,
 0.2182178902359924,
 0.2182178902359924,
 0.2182178902359924,
 0.2182178902359924,
 0.2182178902359924,
 0.2182178902359924,
 0.2182178902359924,
 0.2182178902359924,
 0.2182178902359924,
 0.2182178902359924,
 0.2182178902359924,
 0.2182178902359924,
 0.2182178902359924,
 0.2182178902359924,
 0.2182178902359924,
 0.2182178902359924,
 0.2182178902359924,
 0.2182178902359924,
 0.2182178902359924,
 0.2182178902359924,
 0.2182178902359924,
 0.2182178902359924,
 0.2182178902359924,
 0.2182178902359924,
 0.2182178902359924,
 0.2182178902359924,
 0.2182178902359924,
 0.2182178902359924,
 0.2182178902359924,
 0.2182178902359924,
 0.2182178902359924,
 0.2182178902359924,
 0.2182178902359924,
 0.2182178902359924,
 0.2182178902359924,
 0.2182178902359924,
 0.2182178902359924,
 0.2182178902359924,
 0.2182178902359924,
 0.2182178902359924,
 0.2182178902359924,
 0.21821789023599236,
 0.21821789023599236,
 0.21428571428571425,
 0.21428571428571425,
 0.21428571428571425,
 0.21428571428571425,
 0.20965696734438366,
 0.20965696734438366,
 0.20965696734438366,
 0.20965696734438366,
 0.20965696734438366,
 0.20965696734438366,
 0.20965696734438366,
 0.20965696734438366,
 0.20965696734438366,
 0.20965696734438366,
 0.20965696734438366,
 0.20965696734438366,
 0.20965696734438366,
 0.20965696734438366,
 0.20965696734438366,
 0.20965696734438366,
 0.20965696734438366,
 0.20965696734438366,
 0.20965696734438366,
 0.20965696734438366,
 0.20965696734438366,
 0.20965696734438366,
 0.20965696734438366,
 0.20965696734438366,
 0.20965696734438366,
 0.20965696734438366,
 0.20965696734438366,
 0.20965696734438366,
 0.20965696734438366,
 0.20965696734438366,
 0.20965696734438366,
 0.20965696734438366,
 0.20965696734438366,
 0.20965696734438366,
 0.20965696734438366,
 0.20965696734438366,
 0.20965696734438366,
 0.20965696734438366,
 0.20965696734438366,
 0.20965696734438366,
 0.20965696734438366,
 0.20965696734438366,
 0.20965696734438366,
 0.20965696734438366,
 0.20965696734438366,
 0.20965696734438366,
 0.20965696734438366,
 0.20965696734438366,
 0.20965696734438366,
 0.20965696734438366,
 0.20965696734438366,
 0.20965696734438366,
 0.20965696734438366,
 0.20701966780270623,
 0.20701966780270623,
 0.20701966780270623,
 0.20203050891044214,
 0.20203050891044214,
 0.20203050891044214,
 0.20203050891044214,
 0.20203050891044214,
 0.20203050891044214,
 0.20203050891044214,
 0.20203050891044214,
 0.20203050891044214,
 0.20203050891044214,
 0.20203050891044214,
 0.20203050891044214,
 0.20203050891044214,
 0.20203050891044214,
 0.20203050891044214,
 0.20203050891044214,
 0.20203050891044214,
 0.20203050891044214,
 0.20203050891044214,
 0.20203050891044214,
 0.20203050891044214,
 0.20203050891044214,
 0.20203050891044214,
 0.20203050891044214,
 0.20203050891044214,
 0.20203050891044214,
 0.20203050891044214,
 0.20203050891044214,
 0.20203050891044214,
 0.20203050891044214,
 0.20203050891044214,
 0.20203050891044214,
 0.20203050891044214,
 0.20203050891044214,
 0.20203050891044214,
 0.20203050891044214,
 0.20203050891044214,
 0.20203050891044214,
 0.20203050891044214,
 0.20203050891044214,
 0.20203050891044214,
 0.1951800145897066,
 0.1951800145897066,
 0.1951800145897066,
 0.1951800145897066,
 0.1951800145897066,
 0.1951800145897066,
 0.1951800145897066,
 0.1951800145897066,
 0.1951800145897066,
 0.1951800145897066,
 0.1951800145897066,
 0.1951800145897066,
 0.1951800145897066,
 0.1951800145897066,
 0.1951800145897066,
 0.1951800145897066,
 0.1951800145897066,
 0.1951800145897066,
 0.1951800145897066,
 0.1951800145897066,
 0.1951800145897066,
 0.1951800145897066,
 0.1951800145897066,
 0.1951800145897066,
 0.1951800145897066,
 0.1951800145897066,
 0.1951800145897066,
 0.1951800145897066,
 0.1951800145897066,
 0.1951800145897066,
 0.1951800145897066,
 0.1951800145897066,
 0.1951800145897066,
 0.1951800145897066,
 0.1951800145897066,
 0.1951800145897066,
 0.1889822365046136,
 0.1889822365046136,
 0.1889822365046136,
 0.1889822365046136,
 0.1889822365046136,
 0.1889822365046136,
 0.1889822365046136,
 0.1889822365046136,
 0.1889822365046136,
 0.1889822365046136,
 0.1889822365046136,
 0.1889822365046136,
 0.1889822365046136,
 0.1889822365046136,
 0.1889822365046136,
 0.1889822365046136,
 0.1889822365046136,

In [49]:
list(enumerate(similarity[0]))

[(0, 0.9999999999999998),
 (1, 0.08058229640253801),
 (2, 0.2182178902359924),
 (3, 0.1690308509457033),
 (4, 0.08247860988423225),
 (5, 0.0),
 (6, 0.3418817293789138),
 (7, 0.1781741612749496),
 (8, 0.0944911182523068),
 (9, 0.2519763153394848),
 (10, 0.1091089451179962),
 (11, 0.16116459280507603),
 (12, 0.0),
 (13, 0.17342199390482396),
 (14, 0.1649572197684645),
 (15, 0.0563436169819011),
 (16, 0.1259881576697424),
 (17, 0.0),
 (18, 0.0),
 (19, 0.13363062095621217),
 (20, 0.0890870806374748),
 (21, 0.0),
 (22, 0.1543033499620919),
 (23, 0.10482848367219183),
 (24, 0.0),
 (25, 0.0),
 (26, 0.0),
 (27, 0.0944911182523068),
 (28, 0.11396057645963795),
 (29, 0.0975900072948533),
 (30, 0.0),
 (31, 0.0),
 (32, 0.06788442333021306),
 (33, 0.0944911182523068),
 (34, 0.0),
 (35, 0.1889822365046136),
 (36, 0.0),
 (37, 0.0),
 (38, 0.13363062095621217),
 (39, 0.09166984970282112),
 (40, 0.0),
 (41, 0.11952286093343936),
 (42, 0.20965696734438366),
 (43, 0.15118578920369088),
 (44, 0.5714285714285713),
 (45, 0.1889822365046136),
 (46, 0.2279211529192759),
 (47, 0.0),
 (48, 0.0),
 (49, 0.20965696734438366),
 (50, 0.0),
 (51, 0.0),
 (52, 0.0),
 (53, 0.10482848367219183),
 (54, 0.0),
 (55, 0.0),
 (56, 0.13363062095621217),
 (57, 0.0),
 (58, 0.14285714285714282),
 (59, 0.0),
 (60, 0.10482848367219183),
 (61, 0.13363062095621217),
 (62, 0.0),
 (63, 0.0944911182523068),
 (64, 0.0),
 (65, 0.11396057645963795),
 (66, 0.1543033499620919),
 (67, 0.4364357804719848),
 (68, 0.0),
 (69, 0.10101525445522107),
 (70, 0.20203050891044214),
 (71, 0.20203050891044214),
 (72, 0.0),
 (73, 0.2182178902359924),
 (74, 0.09166984970282112),
 (75, 0.1543033499620919),
 (76, 0.0975900072948533),
 (77, 0.4364357804719848),
 (78, 0.14285714285714282),
 (79, 0.1259881576697424),
 (80, 0.0),
 (81, 0.0),
 (82, 0.10101525445522107),
 (83, 0.0),
 (84, 0.0),
 (85, 0.11952286093343936),
 (86, 0.1690308509457033),
 (87, 0.2182178902359924),
 (88, 0.1889822365046136),
 (89, 0.0),
 (90, 0.10482848367219183),
 (91, 0.08247860988423225),
 (92, 0.3779644730092272),
 (93, 0.0),
 (94, 0.0),
 (95, 0.1091089451179962),
 (96, 0.11952286093343936),
 (97, 0.13363062095621217),
 (98, 0.0),
 (99, 0.0),
 (100, 0.13363062095621217),
 (101, 0.14285714285714282),
 (102, 0.16116459280507603),
 (103, 0.11396057645963795),
 (104, 0.0890870806374748),
 (105, 0.0),
 (106, 0.0),
 (107, 0.0975900072948533),
 (108, 0.0),
 (109, 0.0),
 (110, 0.14285714285714282),
 (111, 0.11952286093343936),
 (112, 0.14285714285714282),
 (113, 0.16116459280507603),
 (114, 0.0),
 (115, 0.0),
 (116, 0.0),
 (117, 0.17342199390482396),
 (118, 0.11396057645963795),
 (119, 0.0),
 (120, 0.10101525445522107),
 (121, 0.1889822365046136),
 (122, 0.20203050891044214),
 (123, 0.18333969940564224),
 (124, 0.0890870806374748),
 (125, 0.13363062095621217),
 (126, 0.23904572186687872),
 (127, 0.10482848367219183),
 (128, 0.13363062095621217),
 (129, 0.14285714285714282),
 (130, 0.07715167498104596),
 (131, 0.1259881576697424),
 (132, 0.13363062095621217),
 (133, 0.1690308509457033),
 (134, 0.20965696734438366),
 (135, 0.0),
 (136, 0.1091089451179962),
 (137, 0.11396057645963795),
 (138, 0.0944911182523068),
 (139, 0.1889822365046136),
 (140, 0.10482848367219183),
 (141, 0.1543033499620919),
 (142, 0.15762208124782012),
 (143, 0.0),
 (144, 0.0),
 (145, 0.0),
 (146, 0.0890870806374748),
 (147, 0.07142857142857141),
 (148, 0.3273268353539886),
 (149, 0.13363062095621217),
 (150, 0.0944911182523068),
 (151, 0.3779644730092272),
 (152, 0.07559289460184544),
 (153, 0.2519763153394848),
 (154, 0.3779644730092272),
 (155, 0.0),
 (156, 0.1543033499620919),
 (157, 0.28347335475692037),
 (158, 0.4364357804719848),
 (159, 0.1649572197684645),
 (160, 0.11396057645963795),
 (161, 0.0),
 (162, 0.14285714285714282),
 (163, 0.11952286093343936),
 (164, 0.0975900072948533),
 (165, 0.1091089451179962),
 (166, 0.50709255283711),
 (167, 0.1690308509457033),
 (168, 0.0),
 (169, 0.13363062095621217),
 (170, 0.0),
 (171, 0.0944911182523068),
 (172, 0.10482848367219183),
 (173, 0.08451542547285165),
 (174, 0.14285714285714282),
 (175, 0.1259881576697424),
 (176, 0.11396057645963795),
 (177, 0.2279211529192759),
 (178, 0.14285714285714282),
 (179, 0.1543033499620919),
 (180, 0.4364357804719848),
 (181, 0.0),
 (182, 0.3380617018914066),
 (183, 0.0),
 (184, 0.11952286093343936),
 (185, 0.3903600291794132),
 (186, 0.13363062095621217),
 (187, 0.0),
 (188, 0.0),
 (189, 0.0),
 (190, 0.08058229640253801),
 (191, 0.1259881576697424),
 (192, 0.14285714285714282),
 (193, 0.08451542547285165),
 (194, 0.0),
 (195, 0.2519763153394848),
 (196, 0.0),
 (197, 0.26726124191242434),
 (198, 0.1690308509457033),
 (199, 0.0),
 (200, 0.0),
 (201, 0.0),
 (202, 0.13363062095621217),
 (203, 0.20203050891044214),
 (204, 0.0),
 (205, 0.28571428571428564),
 (206, 0.0890870806374748),
 (207, 0.0),
 (208, 0.1889822365046136),
 (209, 0.0),
 (210, 0.1259881576697424),
 (211, 0.0),
 (212, 0.0),
 (213, 0.1649572197684645),
 (214, 0.3779644730092272),
 (215, 0.08247860988423225),
 (216, 0.1690308509457033),
 (217, 0.0),
 (218, 0.23904572186687872),
 (219, 0.07881104062391006),
 (220, 0.2279211529192759),
 (221, 0.0),
 (222, 0.0),
 (223, 0.3273268353539886),
 (224, 0.11952286093343936),
 (225, 0.14285714285714282),
 (226, 0.11952286093343936),
 (227, 0.1259881576697424),
 (228, 0.09166984970282112),
 (229, 0.14285714285714282),
 (230, 0.1543033499620919),
 (231, 0.23145502494313785),
 (232, 0.1781741612749496),
 (233, 0.0944911182523068),
 (234, 0.11396057645963795),
 (235, 0.0),
 (236, 0.13363062095621217),
 (237, 0.08451542547285165),
 (238, 0.1543033499620919),
 (239, 0.1091089451179962),
 (240, 0.23904572186687872),
 (241, 0.1649572197684645),
 (242, 0.0),
 (243, 0.2279211529192759),
 (244, 0.0),
 (245, 0.0),
 (246, 0.0),
 (247, 0.0),
 (248, 0.0),
 (249, 0.0),
 (250, 0.0),
 (251, 0.0975900072948533),
 (252, 0.10482848367219183),
 (253, 0.0),
 (254, 0.0),
 (255, 0.3086066999241838),
 (256, 0.07412493166611012),
 (257, 0.11396057645963795),
 (258, 0.11396057645963795),
 (259, 0.07881104062391006),
 (260, 0.09166984970282112),
 (261, 0.0),
 (262, 0.0),
 (263, 0.08451542547285165),
 (264, 0.11396057645963795),
 (265, 0.14285714285714282),
 (266, 0.0),
 (267, 0.0),
 (268, 0.0),
 (269, 0.23904572186687872),
 (270, 0.0),
 (271, 0.0),
 (272, 0.1259881576697424),
 (273, 0.0),
 (274, 0.2182178902359924),
 (275, 0.10101525445522107),
 (276, 0.23904572186687872),
 (277, 0.5714285714285713),
 (278, 0.0),
 (279, 0.20203050891044214),
 (280, 0.10101525445522107),
 (281, 0.0),
 (282, 0.0),
 (283, 0.0),
 (284, 0.2279211529192759),
 (285, 0.0),
 (286, 0.0975900072948533),
 (287, 0.0),
 (288, 0.14285714285714282),
 (289, 0.0),
 (290, 0.11952286093343936),
 (291, 0.23904572186687872),
 (292, 0.2279211529192759),
 (293, 0.0),
 (294, 0.0),
 (295, 0.0),
 (296, 0.3380617018914066),
 (297, 0.0),
 (298, 0.0),
 (299, 0.1259881576697424),
 (300, 0.0),
 (301, 0.1690308509457033),
 (302, 0.28571428571428564),
 (303, 0.1091089451179962),
 (304, 0.20965696734438366),
 (305, 0.0),
 (306, 0.26726124191242434),
 (307, 0.0),
 (308, 0.11396057645963795),
 (309, 0.08671099695241198),
 (310, 0.1259881576697424),
 (311, 0.1091089451179962),
 (312, 0.13363062095621217),
 (313, 0.0),
 (314, 0.0975900072948533),
 (315, 0.1259881576697424),
 (316, 0.2182178902359924),
 (317, 0.13363062095621217),
 (318, 0.1690308509457033),
 (319, 0.1091089451179962),
 (320, 0.0),
 (321, 0.0),
 (322, 0.1690308509457033),
 (323, 0.3585685828003181),
 (324, 0.09166984970282112),
 (325, 0.1091089451179962),
 (326, 0.1543033499620919),
 (327, 0.0),
 (328, 0.1259881576697424),
 (329, 0.0),
 (330, 0.14285714285714282),
 (331, 0.09166984970282112),
 (332, 0.20965696734438366),
 (333, 0.08671099695241198),
 (334, 0.2182178902359924),
 (335, 0.11396057645963795),
 (336, 0.2519763153394848),
 (337, 0.0),
 (338, 0.0),
 (339, 0.13363062095621217),
 (340, 0.1889822365046136),
 (341, 0.3086066999241838),
 (342, 0.26726124191242434),
 (343, 0.0),
 (344, 0.3380617018914066),
 (345, 0.1649572197684645),
 (346, 0.24174688920761406),
 (347, 0.07881104062391006),
 (348, 0.20965696734438366),
 (349, 0.08247860988423225),
 (350, 0.1543033499620919),
 (351, 0.0),
 (352, 0.0),
 (353, 0.1091089451179962),
 (354, 0.0),
 (355, 0.2519763153394848),
 (356, 0.0),
 (357, 0.07881104062391006),
 (358, 0.3779644730092272),
 (359, 0.07273929674533079),
 (360, 0.07412493166611012),
 (361, 0.0),
 (362, 0.0),
 (363, 0.14285714285714282),
 (364, 0.0),
 (365, 0.3779644730092272),
 (366, 0.4364357804719848),
 (367, 0.09166984970282112),
 (368, 0.0),
 (369, 0.3086066999241838),
 (370, 0.06052275326688024),
 (371, 0.11396057645963795),
 (372, 0.0),
 (373, 0.0),
 (374, 0.0),
 (375, 0.1091089451179962),
 (376, 0.09166984970282112),
 (377, 0.11952286093343936),
 (378, 0.0975900072948533),
 (379, 0.0),
 (380, 0.0),
 (381, 0.3086066999241838),
 (382, 0.13363062095621217),
 (383, 0.0),
 (384, 0.1259881576697424),
 (385, 0.0),
 (386, 0.11396057645963795),
 (387, 0.10101525445522107),
 (388, 0.08671099695241198),
 (389, 0.08451542547285165),
 (390, 0.0),
 (391, 0.0),
 (392, 0.0),
 (393, 0.08451542547285165),
 (394, 0.0),
 (395, 0.0),
 (396, 0.0),
 (397, 0.0),
 (398, 0.4364357804719848),
 (399, 0.07559289460184544),
 (400, 0.06900655593423541),
 (401, 0.07018624063435963),
 (402, 0.0),
 (403, 0.0),
 (404, 0.10482848367219183),
 (405, 0.0),
 (406, 0.0),
 (407, 0.0),
 (408, 0.28571428571428564),
 (409, 0.20965696734438366),
 (410, 0.11952286093343936),
 (411, 0.14285714285714282),
 (412, 0.2182178902359924),
 (413, 0.0),
 (414, 0.0),
 (415, 0.0),
 (416, 0.1259881576697424),
 (417, 0.1690308509457033),
 (418, 0.11396057645963795),
 (419, 0.07559289460184544),
 (420, 0.23904572186687872),
 (421, 0.0),
 (422, 0.0),
 (423, 0.1091089451179962),
 (424, 0.1543033499620919),
 (425, 0.0),
 (426, 0.11396057645963795),
 (427, 0.0),
 (428, 0.1091089451179962),
 (429, 0.1091089451179962),
 (430, 0.3144854510165755),
 (431, 0.2279211529192759),
 (432, 0.0975900072948533),
 (433, 0.0),
 (434, 0.1543033499620919),
 (435, 0.0),
 (436, 0.0),
 (437, 0.0),
 (438, 0.0),
 (439, 0.0),
 (440, 0.06788442333021306),
 (441, 0.0),
 (442, 0.0),
 (443, 0.0),
 (444, 0.0),
 (445, 0.28571428571428564),
 (446, 0.0),
 (447, 0.1690308509457033),
 (448, 0.0),
 (449, 0.0),
 (450, 0.0975900072948533),
 (451, 0.0),
 (452, 0.11952286093343936),
 (453, 0.0975900072948533),
 (454, 0.0),
 (455, 0.18333969940564224),
 (456, 0.26726124191242434),
 (457, 0.1091089451179962),
 (458, 0.0),
 (459, 0.0),
 (460, 0.0),
 (461, 0.1543033499620919),
 (462, 0.0890870806374748),
 (463, 0.0),
 (464, 0.0),
 (465, 0.0),
 (466, 0.0),
 (467, 0.0),
 (468, 0.0),
 (469, 0.23904572186687872),
 (470, 0.0944911182523068),
 (471, 0.10482848367219183),
 (472, 0.10482848367219183),
 (473, 0.1543033499620919),
 (474, 0.10482848367219183),
 (475, 0.1690308509457033),
 (476, 0.08451542547285165),
 (477, 0.1690308509457033),
 (478, 0.13363062095621217),
 (479, 0.3380617018914066),
 (480, 0.3779644730092272),
 (481, 0.1690308509457033),
 (482, 0.0944911182523068),
 (483, 0.0),
 (484, 0.2182178902359924),
 (485, 0.11952286093343936),
 (486, 0.0),
 (487, 0.0),
 (488, 0.11396057645963795),
 (489, 0.0),
 (490, 0.1889822365046136),
 (491, 0.3779644730092272),
 (492, 0.0),
 (493, 0.0),
 (494, 0.0),
 (495, 0.0),
 (496, 0.10101525445522107),
 (497, 0.14285714285714282),
 (498, 0.11952286093343936),
 (499, 0.0),
 (500, 0.11952286093343936),
 (501, 0.3086066999241838),
 (502, 0.0),
 (503, 0.10482848367219183),
 (504, 0.10101525445522107),
 (505, 0.13363062095621217),
 (506, 0.0),
 (507, 0.0890870806374748),
 (508, 0.0),
 (509, 0.1091089451179962),
 (510, 0.0),
 (511, 0.0),
 (512, 0.0),
 (513, 0.1543033499620919),
 (514, 0.11396057645963795),
 (515, 0.0),
 (516, 0.0),
 (517, 0.11952286093343936),
 (518, 0.11396057645963795),
 (519, 0.3144854510165755),
 (520, 0.1259881576697424),
 (521, 0.1690308509457033),
 (522, 0.26726124191242434),
 (523, 0.23904572186687872),
 (524, 0.20965696734438366),
 (525, 0.0),
 (526, 0.0),
 (527, 0.1259881576697424),
 (528, 0.11952286093343936),
 (529, 0.1889822365046136),
 (530, 0.13363062095621217),
 (531, 0.3086066999241838),
 (532, 0.1259881576697424),
 (533, 0.1690308509457033),
 (534, 0.1543033499620919),
 (535, 0.1690308509457033),
 (536, 0.14285714285714282),
 (537, 0.0),
 (538, 0.07142857142857141),
 (539, 0.18333969940564224),
 (540, 0.17342199390482396),
 (541, 0.15762208124782012),
 (542, 0.11952286093343936),
 (543, 0.0),
 (544, 0.0),
 (545, 0.26726124191242434),
 (546, 0.3779644730092272),
 (547, 0.0),
 (548, 0.3585685828003181),
 (549, 0.28347335475692037),
 (550, 0.0),
 (551, 0.18333969940564224),
 (552, 0.2182178902359924),
 (553, 0.28571428571428564),
 (554, 0.28347335475692037),
 (555, 0.2279211529192759),
 (556, 0.1889822365046136),
 (557, 0.11952286093343936),
 (558, 0.0),
 (559, 0.1259881576697424),
 (560, 0.11952286093343936),
 (561, 0.3418817293789138),
 (562, 0.1889822365046136),
 (563, 0.0),
 (564, 0.11952286093343936),
 (565, 0.2182178902359924),
 (566, 0.13363062095621217),
 (567, 0.0),
 (568, 0.0975900072948533),
 (569, 0.0),
 (570, 0.1091089451179962),
 (571, 0.1543033499620919),
 (572, 0.24743582965269675),
 (573, 0.20965696734438366),
 (574, 0.1091089451179962),
 (575, 0.0),
 (576, 0.26726124191242434),
 (577, 0.0),
 (578, 0.0),
 (579, 0.1543033499620919),
 (580, 0.4558423058385518),
 (581, 0.10482848367219183),
 (582, 0.4558423058385518),
 (583, 0.14285714285714282),
 (584, 0.0),
 (585, 0.0),
 (586, 0.14285714285714282),
 (587, 0.10482848367219183),
 (588, 0.0),
 (589, 0.09166984970282112),
 (590, 0.14285714285714282),
 (591, 0.1889822365046136),
 (592, 0.20203050891044214),
 (593, 0.0),
 (594, 0.0),
 (595, 0.0975900072948533),
 (596, 0.1889822365046136),
 (597, 0.17342199390482396),
 (598, 0.09166984970282112),
 (599, 0.0975900072948533),
 (600, 0.14285714285714282),
 (601, 0.0),
 (602, 0.1690308509457033),
 (603, 0.0944911182523068),
 (604, 0.0),
 (605, 0.15118578920369088),
 (606, 0.0),
 (607, 0.0),
 (608, 0.0),
 (609, 0.1889822365046136),
 (610, 0.10482848367219183),
 (611, 0.1091089451179962),
 (612, 0.0),
 (613, 0.11396057645963795),
 (614, 0.0),
 (615, 0.2182178902359924),
 (616, 0.0944911182523068),
 (617, 0.07559289460184544),
 (618, 0.0),
 (619, 0.5669467095138407),
 (620, 0.13363062095621217),
 (621, 0.11952286093343936),
 (622, 0.1951800145897066),
 (623, 0.0),
 (624, 0.0),
 (625, 0.08058229640253801),
 (626, 0.08671099695241198),
 (627, 0.2519763153394848),
 (628, 0.15762208124782012),
 (629, 0.20203050891044214),
 (630, 0.4285714285714285),
 (631, 0.2182178902359924),
 (632, 0.14285714285714282),
 (633, 0.0944911182523068),
 (634, 0.3779644730092272),
 (635, 0.09100315103865801),
 (636, 0.20965696734438366),
 (637, 0.26726124191242434),
 (638, 0.1889822365046136),
 (639, 0.0),
 (640, 0.0),
 (641, 0.0),
 (642, 0.3585685828003181),
 (643, 0.11952286093343936),
 (644, 0.0),
 (645, 0.10482848367219183),
 (646, 0.1781741612749496),
 (647, 0.1543033499620919),
 (648, 0.0),
 (649, 0.1091089451179962),
 (650, 0.11952286093343936),
 (651, 0.1091089451179962),
 (652, 0.27500954910846337),
 (653, 0.1690308509457033),
 (654, 0.0),
 (655, 0.10101525445522107),
 (656, 0.10101525445522107),
 (657, 0.1259881576697424),
 (658, 0.13363062095621217),
 (659, 0.1690308509457033),
 (660, 0.0),
 (661, 0.2279211529192759),
 (662, 0.0975900072948533),
 (663, 0.08247860988423225),
 (664, 0.1091089451179962),
 (665, 0.14285714285714282),
 (666, 0.10101525445522107),
 (667, 0.0),
 (668, 0.14285714285714282),
 (669, 0.0),
 (670, 0.26726124191242434),
 (671, 0.07273929674533079),
 (672, 0.0),
 (673, 0.09166984970282112),
 (674, 0.0),
 (675, 0.10482848367219183),
 (676, 0.1951800145897066),
 (677, 0.0),
 (678, 0.0),
 (679, 0.0),
 (680, 0.13363062095621217),
 (681, 0.1889822365046136),
 (682, 0.20203050891044214),
 (683, 0.0944911182523068),
 (684, 0.1690308509457033),
 (685, 0.26726124191242434),
 (686, 0.23904572186687872),
 (687, 0.10482848367219183),
 (688, 0.5345224838248487),
 (689, 0.16116459280507603),
 (690, 0.28347335475692037),
 (691, 0.0),
 (692, 0.0),
 (693, 0.0),
 (694, 0.10482848367219183),
 (695, 0.27500954910846337),
 (696, 0.11396057645963795),
 (697, 0.14285714285714282),
 (698, 0.0975900072948533),
 (699, 0.0),
 (700, 0.10482848367219183),
 (701, 0.3144854510165755),
 (702, 0.10101525445522107),
 (703, 0.1259881576697424),
 (704, 0.0),
 (705, 0.2279211529192759),
 (706, 0.11396057645963795),
 (707, 0.0),
 (708, 0.0),
 (709, 0.0),
 (710, 0.0),
 (711, 0.26726124191242434),
 (712, 0.11952286093343936),
 (713, 0.0),
 (714, 0.11396057645963795),
 (715, 0.1259881576697424),
 (716, 0.0975900072948533),
 (717, 0.0),
 (718, 0.0975900072948533),
 (719, 0.0),
 (720, 0.11952286093343936),
 (721, 0.1091089451179962),
 (722, 0.0),
 (723, 0.2279211529192759),
 (724, 0.20965696734438366),
 (725, 0.13363062095621217),
 (726, 0.0),
 (727, 0.17342199390482396),
 (728, 0.1091089451179962),
 (729, 0.0),
 (730, 0.2182178902359924),
 (731, 0.1259881576697424),
 (732, 0.16116459280507603),
 (733, 0.1259881576697424),
 (734, 0.0890870806374748),
 (735, 0.0),
 (736, 0.10482848367219183),
 (737, 0.0),
 (738, 0.0),
 (739, 0.1543033499620919),
 (740, 0.09166984970282112),
 (741, 0.0),
 (742, 0.13363062095621217),
 (743, 0.0),
 (744, 0.13363062095621217),
 (745, 0.0),
 (746, 0.0),
 (747, 0.1543033499620919),
 (748, 0.14285714285714282),
 (749, 0.3086066999241838),
 (750, 0.1091089451179962),
 (751, 0.2182178902359924),
 (752, 0.0),
 (753, 0.0),
 (754, 0.0),
 (755, 0.10482848367219183),
 (756, 0.1889822365046136),
 (757, 0.3086066999241838),
 (758, 0.0),
 (759, 0.1690308509457033),
 (760, 0.1690308509457033),
 (761, 0.1690308509457033),
 (762, 0.3585685828003181),
 (763, 0.11396057645963795),
 (764, 0.3779644730092272),
 (765, 0.13363062095621217),
 (766, 0.0),
 (767, 0.0),
 (768, 0.0),
 (769, 0.1781741612749496),
 (770, 0.13363062095621217),
 (771, 0.1889822365046136),
 (772, 0.0975900072948533),
 (773, 0.08451542547285165),
 (774, 0.1543033499620919),
 (775, 0.1690308509457033),
 (776, 0.10482848367219183),
 (777, 0.0),
 (778, 0.23904572186687872),
 (779, 0.1889822365046136),
 (780, 0.11952286093343936),
 (781, 0.09166984970282112),
 (782, 0.0),
 (783, 0.14285714285714282),
 (784, 0.10101525445522107),
 (785, 0.1259881576697424),
 (786, 0.3779644730092272),
 (787, 0.0),
 (788, 0.22677868380553634),
 (789, 0.20965696734438366),
 (790, 0.1889822365046136),
 (791, 0.13576884666042613),
 (792, 0.14285714285714282),
 (793, 0.0),
 (794, 0.0),
 (795, 0.08451542547285165),
 (796, 0.0944911182523068),
 (797, 0.11952286093343936),
 (798, 0.14285714285714282),
 (799, 0.08671099695241198),
 (800, 0.0),
 (801, 0.07881104062391006),
 (802, 0.1690308509457033),
 (803, 0.10482848367219183),
 (804, 0.0),
 (805, 0.0),
 (806, 0.07559289460184544),
 (807, 0.11396057645963795),
 (808, 0.11396057645963795),
 (809, 0.10101525445522107),
 (810, 0.1259881576697424),
 (811, 0.1543033499620919),
 (812, 0.2182178902359924),
 (813, 0.0),
 (814, 0.1889822365046136),
 (815, 0.0),
 (816, 0.11952286093343936),
 (817, 0.16116459280507603),
 (818, 0.20965696734438366),
 (819, 0.0),
 (820, 0.2279211529192759),
 (821, 0.1091089451179962),
 (822, 0.1543033499620919),
 (823, 0.11396057645963795),
 (824, 0.0),
 (825, 0.3779644730092272),
 (826, 0.07273929674533079),
 (827, 0.0),
 (828, 0.0),
 (829, 0.1543033499620919),
 (830, 0.2182178902359924),
 (831, 0.0),
 (832, 0.11952286093343936),
 (833, 0.3585685828003181),
 (834, 0.0),
 (835, 0.0),
 (836, 0.21428571428571425),
 (837, 0.17342199390482396),
 (838, 0.1951800145897066),
 (839, 0.4364357804719848),
 (840, 0.23904572186687872),
 (841, 0.0944911182523068),
 (842, 0.1259881576697424),
 (843, 0.0),
 (844, 0.07559289460184544),
 (845, 0.0),
 (846, 0.2182178902359924),
 (847, 0.1690308509457033),
 (848, 0.0),
 (849, 0.20203050891044214),
 (850, 0.0),
 (851, 0.0),
 (852, 0.0),
 (853, 0.0),
 (854, 0.08247860988423225),
 (855, 0.0),
 (856, 0.2927700218845599),
 (857, 0.14285714285714282),
 (858, 0.0),
 (859, 0.10482848367219183),

In [50]:
def recommend(movie):
    # Find the index of the given movie title
    movie_index = new_df[new_df['title'] == movie].index[0]

    # Get similarity scores for the movie
    distances = similarity[movie_index]

    # Sort movies based on similarity scores (excluding the first one)
    movies_list = sorted(list(enumerate(distances)), reverse=True, key=lambda x: x[1])[1:6]

    # Print recommended movie titles
    for i in movies_list:
        print(new_df.iloc[i[0]]['title'])

In [51]:
recommend("Spectre")

Invasion U.S.A.
The Marine 4: Moving Target
Tracker
Congo
Extreme Ops

In [52]:
import pandas as pd
import numpy as np
import ast
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity


# Step 1: Data Preprocessing
def convert(obj):
    try:
        obj = ast.literal_eval(obj)  # Convert stringified lists into actual lists
        return [i['name'] for i in obj]
    except:
        return []

df['genres'] = df['genres'].apply(convert)
df['keywords'] = df['keywords'].apply(convert)

# Extract first 3 actors from cast
def extract_cast(obj):
    try:
        obj = ast.literal_eval(obj)
        return [i['name'] for i in obj[:3]]
    except:
        return []

df['cast'] = df['cast'].apply(extract_cast)

# Extract director name from crew
def extract_director(obj):
    try:
        obj = ast.literal_eval(obj)
        for i in obj:
            if i['job'] == 'Director':
                return [i['name']]
        return []
    except:
        return []

df['crew'] = df['crew'].apply(extract_director)

# Convert overview into a list of words
#df['overview'] = df['overview'].fillna("").apply(lambda x: x.split())

df['overview'] = df['overview'].apply(lambda x: " ".join(x) if isinstance(x, list) else x)
df['overview'] = df['overview'].fillna("").apply(lambda x: x.split())  # Now apply split


# Step 2: Feature Engineering
df['tags'] = df['overview'] + df['genres'] + df['keywords'] + df['cast'] + df['crew']
df['tags'] = df['tags'].apply(lambda x: " ".join(x))

# Step 3: Convert Tags into Vectors
cv = CountVectorizer(max_features=5000, stop_words='english')
vectors = cv.fit_transform(df['tags']).toarray()

# Step 4: Compute Cosine Similarity
similarity = cosine_similarity(vectors)

# Step 5: Movie Recommendation Function
def recommend(movie):
    if movie not in df['title'].values:
        print("Movie not found in database!")
        return
    
    movie_index = df[df['title'] == movie].index[0]
    distances = similarity[movie_index]
    
    # Get top 5 most similar movies (excluding itself)
    movies_list = sorted(list(enumerate(distances)), reverse=True, key=lambda x: x[1])[1:6]
    
    print(f"Movies similar to '{movie}':")
    for i in movies_list:
        print(df.iloc[i[0]]['title'])

In [53]:
# Example Usage:
recommend("10 Cloverfield Lane")

Movies similar to '10 Cloverfield Lane':
Jingle All the Way
Super Hybrid
Premonition
No Good Deed
Unknown

# DEPLOY

In [54]:
import pickle

# Load the movie dictionary
movie_dict = pickle.load(open("movie_dict.pkl", "rb"))
new_df = pd.DataFrame.from_dict(movie_dict)

# Load the similarity matrix
similarity = pickle.load(open("similarity.pkl", "rb"))

In [55]:
new_df.iloc[539].title

'Blade II'

In [56]:
sorted(list(enumerate(similarity[0])), reverse=True, key=lambda x: x[1])[1:6]

[(1471, 0.6761234037828132),
 (4498, 0.6546536707079772),
 (44, 0.5714285714285713),
 (277, 0.5714285714285713),
 (619, 0.5669467095138407)]

In [57]:
new_df[new_df['title']=="Batman Begins"].index[0]

440

In [58]:
import pickle

In [59]:
pickle.dump(new_df.to_dict(),open("movie_dict.pkl","wb"))

In [60]:
new_df

,movie_id,title,Tags
0,301325,#Horror,drama mysteri horror thriller tarynman natasha...
1,19913,(500) Days of Summer,comedi drama romanc date sex jealousi fight ar...
2,333371,10 Cloverfield Lane,thriller sciencefict drama kidnap bunker paran...
3,345003,10 Days in a Madhouse,drama undercov insaneasylum report carolinebar...
4,4951,10 Things I Hate About You,comedi romanc drama shakespear sister highscho...
...,...,...,...
4804,10664,[REC]Â²,thriller horror religionandsupernatur bloodsam...
4805,1946,eXistenZ,action thriller sciencefict horror videogam ha...
4806,7451,xXx,action adventur thriller sportscar biologicalw...
4807,11679,xXx: State of the Union,action adventur crime drama mysteri thriller w...
4808,8202,Ã†on Flux,action sciencefict martialart dystopia surreal...

In [61]:
pickle.dump(similarity,open("similarity.pkl","wb"))

# PROJECT ENDS HERE